"""empty message

Revision ID: 1102a2577f06
Revises: 4eefec015d48
Create Date: 2025-05-23 00:37:26.118840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1102a2577f06'
down_revision: Union[str, None] = '4eefec015d48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_nickname_key', 'users', type_='unique')
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_nickname_key', 'users', ['nickname'])
    # ### end Alembic commands ###
