"""empty message

Revision ID: 9319385f7d4a
Revises: 8512c14bf59e
Create Date: 2025-05-04 21:16:20.380758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9319385f7d4a'
down_revision: Union[str, None] = '8512c14bf59e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diaries', sa.Column('emotion', sa.String(length=50), nullable=True))
    op.add_column('diaries', sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diaries', 'keywords')
    op.drop_column('diaries', 'emotion')
    # ### end Alembic commands ###
