"""Add updated_at to Diary

Revision ID: 8512c14bf59e
Revises: cd69072296dc
Create Date: 2025-04-30 00:08:58.026802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8512c14bf59e'
down_revision: Union[str, None] = 'cd69072296dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diaries', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diaries', 'updated_at')
    # ### end Alembic commands ###
